// Test file for username content moderation
// This can be run manually to test the content moderation functionality

const testUsernames = [
  // Valid usernames (should pass)
  "validUser123",
  "test_user",
  "user-name",
  "gamer123",
  "player_2024",
  
  // Invalid usernames (should be blocked)
  'ejaculate',
  'ejaculation',
  'arsehead',
  'arse',
  'arsehole',
  'asshat',
  'assfart',
  'shite',
  'dumbass',
  'dumb fuck',
  'dyke',
  'load of shit',
  'full of shit',
  'horseshit',
  'dogshit',
  'son of a bitch',
  'son of a whore',
  'prick',
  'shit',
  'shithead',
  'fuck face',
  'finger yourself',
  'Satan',
  'Nazi',
  'Vladimir Putin',
  'Kremlin',
  'Putin',
  'Pro-Putin',
  'Pro-Russia',
  'Benjamin Netanyahu',
  'Viktor Orbán',
  'Xi Jinping',
  'Ayatollah Ali Khamenei',
  'Ahmed al‑Sharaa',
  'Adolf Hitler',
  'Hitler',
  'Augusto Pinochet',
  'Alberto Fujimori',
  'Lee Kuan Yew',
  'Recep Tayyip Erdoğan',
  'Boris Yeltsin',
  'unified reich',
  'Donald Trump',
  'Trump',
  'Trumpism',
  'Trump2028',
  'Make America Great Again',
  'Maga',
  'Mein Kampf',
  'fascist',
  'faggot',
  'fuck',
  'fuck you',
  'fuck off',
  'fuck me',
  'fucking',
  'bastard',
  'spastic',
  'retard',
  'retarded',
  'bitch',
  'pussy',
  'asshole',
  'ass',
  'anal',
  'anus',
  'dick',
  'dickhead',
  'cunt',
  'penis',
  'penal',
  'scrotum',
  'vagina',
  'dildo',
  'neo-nazi',
  'proud boys',
  'oathkeepers',
  'Al Qaeda',
  'Taliban',
  'ISIS',
  'Qatar',
  'Osama Bin Laden',
  'qanon',
  'cum',
  'cumming',
  'Kim Jong Un',
  'Hamas',
  'Bashar al-Assad',
  'Hayʼat Tahrir al-Sham',
  'Hezbollah',
  'Houthi',
  'wanker',
  'whore',
  'white power',
  'white supremacy',
  'white supremacist',
  'coon',
  'cocksucker',
  'nigga',
  'nigger',
  'Stalin',
  'Hentai',
  'porn',
  'pornhub',
  'pornography',
  'pornographic',
  'pedo',
  'pedophile',
  'kill yourself',
  'kys',
  'rape',
  'rapist',
  'raped',
  'fucked',
  'fucked up',
  'motherfucker',
  'motherfucking',
  'J.D. Vance',
  'Elon Musk',
  'Tulsi Gabbard',
  'Tucker Carlson',
  'Jesse Watters',
  'Kari Lake',
  'Marco Rubio',
  'Jeffrey Epstein',
  'Ghislaine Maxwell',
  'Rudy Giuliani',
  'Linda McMahon',
  'Chuck Grassley',
  'Steve Bannon',
  'Tim Scott',
  'Niki Haley',
  'Asa Hutchinson',
  'Francis Suarez',
  'Will Hurd',
  'Perry Johnson',
  'Vivek Ramaswamy',
  'Kash Patel',
  'Dan Bongino',
  'Paul Dans',
  'Winsome Earle-Sears',
  'Mike Johnson',
  'Kyle Rittenhouse',
  'Rick Scott',
  'Ron DeSantis',
  'Casey DeSantis',
  'Pam Bondi',
  'Emil Bove',
  'Pete Hegseth',
  'Ted Cruz',
  'Robert F. Kennedy Jr.',
  'Byron Donalds',
  'Russel Vought',
  'Jon Voight',
  'Marjorie Taylor Greene',
  'Joe Wilson',
  'Lauren Boebert',
  'Matt Gaetz',
  'Alice Johnson',
  'Jim Jordan',
  'Melania Trump',
  'Donald Trump Jr.',
  'Laura Trump',
  'Eric Trump',
  'Ivanka Trump',
  'Mitch McConnell',
  'Doug Burgum',
  'Tom Homan',
  'John Roberts',
  'Amy Coney Barrett',
  'Clarence Thomas',
  'Lindsey Graham',
  'Samuel Alito',
  'Brett Kavanaugh',
  'Neil Gorsuch',
  'Aileen Cannon',
  'Tommy Tuberville',
  'Brandon Carr',
  'Dr. Oz',
  'Mehmet Oz',
  'Julie Fedorchak',
  'Greg Abbott',
  'Enrique Tarrio',
  'Steward Rhodes',
  'Eric Adams',
  'Brad Schimel',
  'Katie Britt',
  'Bernie Mareno',
  'Tom Cotton',
  'Gabe Evans',
  'Rand Paul',
  'Bill Cassidy',
  'Markwayne Mullin',
  'John Thune',
  'Michael Todd Chrisley',
  'Julie Chrisley',
  'Kelly Ayotte',
  'Larry Kudlow',
  'John Barraso',
  'Sarah Palin',
  'Robert Aderholt',
  'James Lankford',
  'Steve Scalise',
  'Kanye West',
  'Bill Cosby',
  'Ben Shapiro',
  'Derek Chauvin',
  'Karoline Leavitt',
  'Dave McCormick',
  'John Eastman',
  'Kenneth Chesebro',
  'Sidney Powell',
  'Mark Meadows',
  'Howard Lutnick',
  'Mike Waltz',
  'Tim Sheehy',
  'John Ratcliffe',
  'Steve Witkoff',
  'Laura Loomer',
  'Rush Limbaugh',
  'Mike Kehoe',
  'Brian Kemp',
  'Alina Habba',
  'Chip Roy',
  'David Richardson',
  'Kristi Noem',
  'Elise Stefanik',
  'Boris Epstein',
  'Ed Martin',
  'Sean Duffy',
  'Jim Banks',
  'Susan Collins',
  'Robert Giuffra',
  'Mike Lindell',
  'Harmeet Dhillon',
  'Ryan Walters',
  'Felix Barry Moore',
  'Jeanine Pirro',
  'J. K. Rowling',
  'Mike Haridopolos',
  'Josh Hawley',
  'Derek Schmidt',
  'Jefferson Shreve',
  'Mike Lee',
  'John Kennedy',
  'Craig Goldman',
  'Derrick Van Orden',
  'Jeff Bezos',
  'Scott Bessent',
  'John Curtis',
  'Lisa McClain',
  'Brooke Rollins',
  'Dabney Friedrich',
  'Jeff Sessions',
  'Richard Hudson Jr.',
  'Andrea Lucas',
  'Mike Flood',
  'Kelly Armstrong',
  'Devin Nunes',
  'Hulk Hogan',
  'Kevin Roberts',
  'Mike Braun',
  'Rodney Scott',
  'Steve Moore',
  'Jeffrey Crank',
  'Robert Wolf',
  'Andrew Puzder',
  'Joshua Divine',
  'Salvatore Cordileone',
  'Vance Boelter',
  'Charlie Kirk',
  'Kevin Stitt',
  'Paul Szypula',
  'Bill Hagerty',
  'Jeff Landry',
  'Nick Sortor',
  'Haile McAnally',
  'Thom Tillis',
  'Joe Lombardo',
  'Kevin Kiley',
  'Anna Paulina',
  'Stephen Miller',
  'Jason Smith',
  'John Sauer',
  'Zach Rehl',
  'Jessica Watkins',
  'Kenneth Harrelson',
  'Kyle Young',
  'James Ho',
  'Don Willett',
  'Henry McMaster',
  'Larry Rhoden',
  'Ashley Moody',
  'Mike DeWine',
  'Robert Morss',
  'Kelly Meggs',
  'Greg Gutfeld',
  'Joseph Hackett',
  'Gary Palmer',
  'Dominic Pezzola',
  'Tim Hale',
  'Sean Combs',
  'Dustin Burrows',
  'Bret Baier',
  'Marlin Stutzman',
  'Elliot Gaiser',
  'Dale Strong',
  'Joni Ernst',
  'Andy Harris',
  'Nancy Mace',
  'Bruce Westerman',
  'Brendan Carr',
  'John Cornyn',
  'Sarah Huckabee Sanders',
  'Gregory Katsas',
  'Justin Walker',
  'Steve Womack',
  'Alex Stein',
  'Tate Reeves',
  'Greg Gianforte',
  'Jeffrey Wall',
  'Marsha Blackburn',
  'Bill Lee',
  'Tony Fabrizio',
  'Markwayne Mullin',
  'Kay Ivey',
  'Jim Pellin',
  'Debra Fischer',
  'Jon Husted',
  'Sheri Biggs',
  'Chris LaCivita',
  'Jimmy Patronis Jr.',
  'Randy Fine',
  'Shelley Moore Capito',
  'James Comer',
  'Glenn Youngkin',
  'Phil McGraw',
  'Bryan Steil',
  'Virginia Foxx',
  'Rick Snyder',
  'Mike Rogers',
  'Addison McDowell',
  'John Boozman',
  'Nick Begich III',
  'Brad Little',
  'Mark Gordon',
  'Phil Scott',
  'Spencer Cox',
  'Kim Reynolds',
  'Ashley Moore',
  'Patrick Harrigan',
  'Jim Justice',
  'Thomas Barrett',
  'David Valadao',
  'Kandiss Taylor',
  'James Murphy',
  'Scott Mayer',
  'Ryan Mackenzie',
  'Rob Bresnahan',
  'Jordan Emery Pratt',
  'Laura Ingraham',
  'Troy Downing',
  'Sean Hannity',
  'Glenn Beck',
  'Charlie Hurt',
  'Mike Dunleavy',
  'Joe Rogan',
  'Alex Jones',
  'Liz Wheeler',
  'Megyn Kelly',
  'Bryan Kohberger',
  'Robert Durst',
  'Ted Bundy',
  'herpes',
  'genitalia',
  'genitals',
  'sex trafficking',
  'kiss my ass',
  'suck my dick',
  'eat a dick',
  'blew my load',
  'blewmyload',
  'titty fuck',
  'titty',
  'nipples',
  'paizuri',
  'shotacon',
  'butt plug',
  'buttplug',
  'Ku Klux Klan',
  'KKK',
  'Department of Government Effeciency',
  'Lynching',
  'buttlicker',
  'jizz',
  'cumshot',
  'blowjob',
  'titties',
  'titjob',
  'handjob',
  'thighjob',
  'footjob',
  'cunnilingus',
  'butt fuck',
  'buttfuck',
  'bitch tits',
  'bitch ass',
  'masterbate',
  'masterbating',
  'masterbated',
  'horny',
  'horny bitch',
  'slut',
  'slutty',
  'Bollocks',
  'bollocks',
  'cumdumpster',
  'cum dumpster',
  'testicles',
  'neek',
  'twat',
  'gooning',
  'buttfucker',
  'butt fucker',
  'buttfucked',
  'butt fucked',
  'pussy hole',
  'blow me',
  'blowme',
  'Children\'s Health Defense',
  'Medical Ethics Defense Act',
  'The Federalist Society',
  'Heritage Foundation',
  'Fox News',
  'One America News Network',
  'Project 2025',
  'National Socialist Movement',
  'Order of the Black Sun',
  'Blood Tribe',
  'Patriot Front',
  'Atomwaffen Division',
  'Phyllis Schlafly Eagles',
  'Religious Liberty Commission'
];

console.log("Username Content Moderation Test");
console.log("=================================");
console.log("This test checks if usernames would be blocked by content moderation");
console.log("");

// Test function to simulate the content moderation check
function testUsername(username) {
  const OFFENSIVE_WORDS = [
    'ejaculate', 'ejaculation', 'arsehead', 'arse', 'arsehole', 'asshat', 'assfart', 'shite', 'dumbass', 'dumb fuck', 'dyke', 'load of shit', 'full of shit', 'horseshit', 'dogshit', 'son of a bitch', 'son of a whore', 'prick', 'shit', 'shithead', 'fuck face', 'finger yourself', 'Satan', 'Nazi', 'Vladimir Putin', 'Kremlin', 'Putin', 'Pro-Putin', 'Pro-Russia', 'Benjamin Netanyahu', 'Viktor Orbán', 'Xi Jinping', 'Ayatollah Ali Khamenei', 'Ahmed al‑Sharaa', 'Adolf Hitler', 'Hitler', 'Augusto Pinochet', 'Alberto Fujimori', 'Lee Kuan Yew', 'Recep Tayyip Erdoğan', 'Boris Yeltsin', 'unified reich', 'Donald Trump', 'Trump', 'Trumpism', 'Trump2028', 'Make America Great Again', 'Maga', 'Mein Kampf', 'fascist', 'faggot', 'fuck', 'fuck you', 'fuck off', 'fuck me', 'fucking', 'bastard', 'spastic', 'retard', 'retarded', 'bitch', 'pussy', 'asshole', 'ass', 'anal', 'anus', 'dick', 'dickhead', 'cunt', 'penis', 'penal', 'scrotum', 'vagina', 'dildo', 'neo-nazi', 'proud boys', 'oathkeepers', 'Al Qaeda', 'Taliban', 'ISIS', 'Qatar', 'Osama Bin Laden', 'qanon', 'cum', 'cumming', 'Kim Jong Un', 'Hamas', 'Bashar al-Assad', 'Hayʼat Tahrir al-Sham', 'Hezbollah', 'Houthi', 'wanker', 'whore', 'white power', 'white supremacy', 'white supremacist', 'coon', 'cocksucker', 'nigga', 'nigger', 'Stalin', 'Hentai', 'porn', 'pornhub', 'pornography', 'pornographic', 'pedo', 'pedophile', 'kill yourself', 'kys', 'rape', 'rapist', 'raped', 'fucked', 'fucked up', 'motherfucker', 'motherfucking', 'J.D. Vance', 'Elon Musk', 'Tulsi Gabbard', 'Tucker Carlson', 'Jesse Watters', 'Kari Lake', 'Marco Rubio', 'Jeffrey Epstein', 'Ghislaine Maxwell', 'Rudy Giuliani', 'Linda McMahon', 'Chuck Grassley', 'Steve Bannon', 'Tim Scott', 'Niki Haley', 'Asa Hutchinson', 'Francis Suarez', 'Will Hurd', 'Perry Johnson', 'Vivek Ramaswamy', 'Kash Patel', 'Dan Bongino', 'Paul Dans', 'Winsome Earle-Sears', 'Mike Johnson', 'Kyle Rittenhouse', 'Rick Scott', 'Ron DeSantis', 'Casey DeSantis', 'Pam Bondi', 'Emil Bove', 'Pete Hegseth', 'Ted Cruz', 'Robert F. Kennedy Jr.', 'Byron Donalds', 'Russel Vought', 'Jon Voight', 'Marjorie Taylor Greene', 'Joe Wilson', 'Lauren Boebert', 'Matt Gaetz', 'Alice Johnson', 'Jim Jordan', 'Melania Trump', 'Donald Trump Jr.', 'Laura Trump', 'Eric Trump', 'Ivanka Trump', 'Mitch McConnell', 'Doug Burgum', 'Tom Homan', 'John Roberts', 'Amy Coney Barrett', 'Clarence Thomas', 'Lindsey Graham', 'Samuel Alito', 'Brett Kavanaugh', 'Neil Gorsuch', 'Aileen Cannon', 'Tommy Tuberville', 'Brandon Carr', 'Dr. Oz', 'Mehmet Oz', 'Greg Abbott', 'Enrique Tarrio', 'Steward Rhodes', 'Eric Adams', 'Brad Schimel', 'Katie Britt', 'Tom Cotton', 'Rand Paul', 'Bill Cassidy', 'Markwayne Mullin', 'John Thune', 'Michael Todd Chrisley', 'Julie Chrisley', 'Larry Kudlow', 'John Barraso', 'Sarah Palin', 'James Lankford', 'Steve Scalise', 'Kanye West', 'Bill Cosby', 'Ben Shapiro', 'Derek Chauvin', 'Karoline Leavitt', 'John Eastman', 'Kenneth Chesebro', 'Sidney Powell', 'Mark Meadows', 'Howard Lutnick', 'Mike Waltz', 'John Ratcliffe', 'Steve Witkoff', 'Laura Loomer', 'Rush Limbaugh', 'Alina Habba', 'Chip Roy', 'David Richardson', 'Kristi Noem', 'Elise Stefanik', 'Boris Epstein', 'Ed Martin', 'Sean Duffy', 'Susan Collins', 'Robert Giuffra', 'Mike Lindell', 'Harmeet Dhillon', 'Ryan Walters', 'Jeanine Pirro', 'J. K. Rowling', 'Josh Hawley', 'Mike Lee', 'John Kennedy', 'Derrick Van Orden', 'Jeff Bezos', 'Scott Bessent', 'Lisa McClain', 'Brooke Rollins', 'Dabney Friedrich', 'Jeff Sessions', 'Andrea Lucas', 'Mike Flood', 'Devin Nunes', 'Kevin Roberts', 'Rodney Scott', 'Steve Moore', 'Robert Wolf', 'Andrew Puzder', 'Joshua Divine', 'Salvatore Cordileone', 'Vance Boelter', 'Charlie Kirk', 'Paul Szypula', 'Bill Hagerty', 'Nick Sortor', 'Haile McAnally', 'Thom Tillis', 'Kevin Kiley', 'Anna Paulina', 'Stephen Miller', 'Jason Smith', 'John Sauer', 'Zach Rehl', 'Jessica Watkins', 'Kenneth Harrelson', 'Kyle Young', 'James Ho', 'Don Willett', 'Ashley Moody', 'Mike DeWine', 'Robert Morss', 'Kelly Meggs', 'Greg Gutfeld', 'Joseph Hackett', 'Dominic Pezzola', 'Tim Hale', 'Sean Combs', 'Dustin Burrows', 'Bret Baier', 'Elliot Gaiser', 'Joni Ernst', 'Andy Harris', 'Nancy Mace', 'Brendan Carr', 'John Cornyn', 'Sarah Huckabee Sanders', 'Gregory Katsas', 'Justin Walker', 'Alex Stein', 'Jeffrey Wall', 'Marsha Blackburn', 'Tony Fabrizio', 'Markwayne Mullin', 'Debra Fischer', 'Jon Husted', 'Chris LaCivita', 'Jimmy Patronis Jr.', 'Randy Fine', 'Shelley Moore Capito', 'James Comer', 'Phil McGraw', 'Bryan Steil', 'Virginia Foxx', 'Rick Snyder', 'Mike Rogers', 'John Boozman', 'Ashley Moore', 'Jim Justice', 'David Valadao', 'Kandiss Taylor', 'James Murphy', 'Scott Mayer', 'Jordan Emery Pratt', 'Laura Ingraham', 'Sean Hannity', 'Glenn Beck', 'Charlie Hurt', 'Joe Rogan', 'Alex Jones', 'Liz Wheeler', 'Megyn Kelly', 'Bryan Kohberger', 'Robert Durst', 'Ted Bundy', 'herpes', 'genitalia', 'genitals', 'sex trafficking', 'kiss my ass', 'suck my dick', 'eat a dick', 'blew my load', 'blewmyload', 'titty fuck', 'titty', 'nipples', 'paizuri', 'shotacon', 'butt plug', 'buttplug', 'Ku Klux Klan', 'KKK', 'Department of Government Effeciency', 'Lynching', 'buttlicker', 'jizz', 'cumshot', 'blowjob', 'titties', 'titjob', 'handjob', 'thighjob', 'footjob', 'cunnilingus', 'butt fuck', 'buttfuck', 'bitch tits', 'bitch ass', 'masterbate', 'masterbating', 'masterbated', 'horny', 'horny bitch', 'slut', 'slutty', 'Bollocks', 'bollocks', 'cumdumpster', 'cum dumpster', 'testicles', 'neek', 'twat', 'gooning', 'buttfucker', 'butt fucker', 'buttfucked', 'butt fucked', 'pussy hole', 'blow me', 'blowme', 'Medical Ethics Defense Act', 'The Federalist Society', 'Heritage Foundation', 'Fox News', 'One America News Network', 'Project 2025', 'National Socialist Movement', 'Order of the Black Sun', 'Blood Tribe', 'Patriot Front', 'Atomwaffen Division', 'Phyllis Schlafly Eagles', 'Religious Liberty Commission', 'Children\'s Health Defense', 'Mike Dunleavy', 'Rob Bresnahan', 'Troy Downing', 'Ryan Mackenzie', 'Thomas Barrett', 'Patrick Harrigan', 'Kim Reynolds', 'Spencer Cox', 'Phil Scott', 'Mark Gordon', 'Brad Little', 'Nick Begich III', 'Addison McDowell', 'Glenn Youngkin', 'Sheri Biggs', 'Jim Pellin', 'Kay Ivey', 'Greg Gianforte', 'Tate Reeves', 'Steve Womack', 'Bruce Westerman', 'Dale Strong', 'Marlin Stutzman', 'Gary Palmer', 'Larry Rhoden', 'Henry McMaster', 'Joe Lombardo', 'Jeff Landry', 'Kevin Stitt', 'Jeffrey Crank', 'Mike Braun', 'Hulk Hogan', 'Kelly Armstrong', 'Richard Hudson Jr.', 'John Curtis', 'Craig Goldman', 'Jefferson Shreve', 'Derek Schmidt', 'Mike Haridopolos', 'Felix Barry Moore', 'Jim Banks', 'Brian Kemp', 'Mike Kehoe', 'Tim Sheehy', 'Dave McCormick', 'Robert Aderholt', 'Kelly Ayotte', 'Gabe Evans', 'Bernie Mareno', 'Julie Fedorchak', 'Corey Lewandowski', 'Dean Cain', 'Ken Paxton', 'Miley Biggs', 'Aligator Alcatraz', 'Doug Collins'
  ];

  const lowercaseUsername = username.toLowerCase();
  const foundWords = OFFENSIVE_WORDS.filter(word => 
    lowercaseUsername.includes(word.toLowerCase())
  );

  return {
    username,
    isOffensive: foundWords.length > 0,
    offendingWords: foundWords
  };
}

// Run tests
let passedTests = 0;
let failedTests = 0;

testUsernames.forEach((username, index) => {
  const result = testUsername(username);
  
  if (index < 5) {
    // First 5 are valid usernames
    if (result.isOffensive) {
      console.log(`❌ FAIL: "${username}" should be valid but was flagged as offensive`);
      failedTests++;
    } else {
      console.log(`✅ PASS: "${username}" is correctly valid`);
      passedTests++;
    }
  } else {
    // Rest are invalid usernames
    if (result.isOffensive) {
      console.log(`✅ PASS: "${username}" is correctly flagged as offensive`);
      passedTests++;
    } else {
      console.log(`❌ FAIL: "${username}" should be offensive but was not flagged`);
      failedTests++;
    }
  }
});

console.log("");
console.log("Test Results:");
console.log(`✅ Passed: ${passedTests}`);
console.log(`❌ Failed: ${failedTests}`);
console.log(`Total: ${passedTests + failedTests}`);

if (failedTests === 0) {
  console.log("🎉 All tests passed! Content moderation is working correctly.");
} else {
  console.log("⚠️  Some tests failed. Please review the content moderation implementation.");
} 