// This is a list of words/names/phrases that are considered offensive and should not be used in this application.
// const OFFENSIVE_WORDS = [
//   'ejaculate',
//   'ejaculation',
//   'shit',
//   'shithead',
//   'fuck face',
//   'finger yourself',
//   'Satan',
//   'Nazi',
//   'Vladimir Putin',
//   'Putin',
//   'Benjamin Netanyahu',
//   'Viktor Orbán',
//   'Xi Jinping',
//   'Adolf Hitler',
//   'Hitler',
//   'Donald Trump',
//   'Trump',
//   'Maga',
//   'fascist',
//   'faggot',
//   'fuck',
//   'fuck you',
//   'fuck off',
//   'bastard',
//   'spastic',
//   'retard',
//   'retarded',
//   'bitch',
//   'pussy',
//   'asshole',
//   'ass',
//   'anal',
//   'anus',
//   'dick',
//   'dickhead',
//   'cunt',
//   'penis',
//   'penal',
//   'scrotum',
//   'vagina',
//   'dildo',
//   'neo-nazi',
//   'proud boys',
//   'oathkeepers',
//   'Al Qaeda',
//   'ISIS',
//   'Osama Bin Laden',
//   'qanon',
//   'cum',
//   'cumming',
//   'Kim Jong Un',
//   'Hamas',
//   'Hezbollah',
//   'Houthi',
//   'wanker',
//   'whore',
//   'white power',
//   'white supremacy',
//   'white supremacist',
//   'coon',
//   'cocksucker',
//   'nigga',
//   'nigger',
//   'Stalin',
//   'Hentai',
//   'porn',
//   'pornhub',
//   'pornography',
//   'pornographic',
//   'pedo',
//   'pedophile',
//   'kill yourself',
//   'rape',
//   'rapist',
//   'raped',
//   'fucked',
//   'fucked up',
//   'J.D. Vance',
//   'Elon Musk',
//   'Tulsi Gabbard',
//   'Tucker Carlson',
//   'Marco Rubio',
//   'Steve Bannon',
//   'Kash Patel',
//   'Mike Johnson',
//   'Kyle Rittenhouse',
//   'Rick Scott',
//   'Ron DeSantis',
//   'Pam Bondi',
//   'Pete Hegseth',
//   'Ted Cruz',
//   'Robert F. Kennedy Jr.',
//   'Russel Vought',
//   'Margery Taylor Greene',
//   'Lauren Boebert',
//   'Matt Gaetz',
//   'Jim Jordan',
//   'Donald Trump Jr.',
//   'Eric Trump',
//   'Mitch McConnell',
//   'Clarence Thomas',
//   'Lindsey Graham',
//   'Samuel Alito',
//   'Brett Kavanaugh',
//   'Neil Gorsuch',
//   'Aileen Cannon',
//   'Tommy Tuberville',
//   'herpes',
//   'genitalia',
//   'genitals',
//   'sex trafficking',
//   'kiss my ass',
//   'suck my dick',
//   'blew my load',
//   'titty fuck',
//   'nipples',
//   'butt plug',
//   'Ku Klux Klan',
//   'KKK',
//   'Lynching',
//   'buttlicker',
//   'jizz',
//   'cumshot',
//   'blowjob',
//   'titties',
//   'titjob',
//   'handjob',
//   'butt fuck',
//   'D.O.G.E'
//   // I do not approve any of these words, names, and or phrases being used in the application.
// ];

// import { handleContentViolation } from './violationHandler';

// export const containsOffensiveContent = async (text: string, userId: string): Promise<{ 
//   isOffensive: boolean; 
//   offendingWords: string[];
//   violationResult?: any;
// }> => {
//   const words = text.toLowerCase().split(/\s+/);
//   const offendingWords = words.filter(word => OFFENSIVE_WORDS.includes(word));
  
//   if (offendingWords.length > 0) {
//     const violationResult = await handleContentViolation(userId, offendingWords);
//     return {
//       isOffensive: true,
//       offendingWords,
//       violationResult
//     };
//   }
  
//   return {
//     isOffensive: false,
//     offendingWords: []
//   };
// }; 