import mongoose from 'mongoose';
import { handleContentViolation } from './violationHandler';

// This is a list of words/names/phrases that are considered offensive and should not be used in this application.
const OFFENSIVE_WORDS = [
  'ejaculate',
  'ejaculation',
  'arsehead',
  'arse',
  'arsehole',
  'shite',
  'dumbass',
  'dumb fuck',
  'dyke',
  'load of shit',
  'full of shit',
  'horseshit',
  'dogshit',
  'son of a bitch',
  'son of a whore',
  'prick',
  'shit',
  'shithead',
  'fuck face',
  'finger yourself',
  'Satan',
  'Nazi',
  'Vladimir Putin',
  'Kremlin',
  'Putin',
  'Pro-Putin',
  'Pro-Russia',
  'Benjamin Netanyahu',
  'Viktor Orbán',
  'Xi Jinping',
  'Adolf Hitler',
  'Hitler',
  'Augusto Pinochet',
  'Alberto Fujimori',
  'Lee Kuan Yew',
  'Recep Tayyip Erdoğan',
  'Boris Yeltsin',
  'unified reich',
  'Donald Trump',
  'Trump',
  'Maga',
  'fascist',
  'faggot',
  'fuck',
  'fuck you',
  'fuck off',
  'fuck me',
  'fucking',
  'bastard',
  'spastic',
  'retard',
  'retarded',
  'bitch',
  'pussy',
  'asshole',
  'ass',
  'anal',
  'anus',
  'dick',
  'dickhead',
  'cunt',
  'penis',
  'penal',
  'scrotum',
  'vagina',
  'dildo',
  'neo-nazi',
  'proud boys',
  'oathkeepers',
  'Al Qaeda',
  'Taliban',
  'ISIS',
  'Osama Bin Laden',
  'qanon',
  'cum',
  'cumming',
  'Kim Jong Un',
  'Hamas',
  'Hezbollah',
  'Houthi',
  'wanker',
  'whore',
  'white power',
  'white supremacy',
  'white supremacist',
  'coon',
  'cocksucker',
  'nigga',
  'nigger',
  'Stalin',
  'Hentai',
  'porn',
  'pornhub',
  'pornography',
  'pornographic',
  'pedo',
  'pedophile',
  'kill yourself',
  'kys',
  'rape',
  'rapist',
  'raped',
  'fucked',
  'fucked up',
  'J.D. Vance',
  'Elon Musk',
  'Tulsi Gabbard',
  'Tucker Carlson',
  'Jesse Watters',
  'Kari Lake',
  'Marco Rubio',
  'Rudy Giuliani',
  'Linda McMahon',
  'Chuck Grassley',
  'Steve Bannon',
  'Tim Scott',
  'Vivek Ramaswamy',
  'Kash Patel',
  'Mike Johnson',
  'Kyle Rittenhouse',
  'Rick Scott',
  'Ron DeSantis',
  'Pam Bondi',
  'Pete Hegseth',
  'Ted Cruz',
  'Robert F. Kennedy Jr.',
  'Byron Donalds',
  'Russel Vought',
  'Margery Taylor Greene',
  'Lauren Boebert',
  'Matt Gaetz',
  'Alice Johnson',
  'Jim Jordan',
  'Donald Trump Jr.',
  'Eric Trump',
  'Mitch McConnell',
  'Clarence Thomas',
  'Lindsey Graham',
  'Samuel Alito',
  'Brett Kavanaugh',
  'Neil Gorsuch',
  'Aileen Cannon',
  'Tommy Tuberville',
  'Dr. Oz',
  'Greg Abbott',
  'Enrique Tarrio',
  'Steward Rhodes',
  'Eric Adams',
  'Brad Schimel',
  'Katie Britt',
  'Tom Cotton',
  'Rand Paul',
  'Bill Cassidy',
  'John Thune',
  'John Barraso',
  'James Lankford',
  'Steve Scalise',
  'Michele Waltz',
  'Kanye West',
  'herpes',
  'genitalia',
  'genitals',
  'sex trafficking',
  'kiss my ass',
  'suck my dick',
  'eat a dick',
  'blew my load',
  'titty fuck',
  'nipples',
  'butt plug',
  'Ku Klux Klan',
  'KKK',
  'Lynching',
  'buttlicker',
  'jizz',
  'cumshot',
  'blowjob',
  'titties',
  'titjob',
  'handjob',
  'butt fuck',
  'D.O.G.E',
  'bitch tits',
  'bitch ass',
  'masterbate',
  'masterbating',
  'masterbated',
  'horny',
  'horny bitch',
  'slut',
  'slutty',
  'Bollocks',
  'cumdumpster',
  'testicles',
  'neek',
  'buttfucker',
  'buttfucked',
  'pussy hole',
  'National Socialist Movement',
  'Order of the Black Sun',
  'Blood Tribe',
  'Patriot Front',
  'Atomwaffen Division'
  // I do not approve any of these words, names, organizations and or phrases being used in this application.
];

export const containsOffensiveContent = async (content: string, userId: string): Promise<{ 
  isOffensive: boolean; 
  offendingWords: string[];
  violationResult?: any;
}> => {
  try {
    if (!mongoose.connection.readyState) {
      await mongoose.connect(process.env.MONGODB_URI as string);
    }
    
    const words = content.toLowerCase().split(/\s+/);
    const offendingWords = words.filter(word => OFFENSIVE_WORDS.includes(word));
    
    if (offendingWords.length > 0) {
      const violationResult = await handleContentViolation(userId, offendingWords);
      return {
        isOffensive: true,
        offendingWords,
        violationResult
      };
    }
    
    return {
      isOffensive: false,
      offendingWords: []
    };
  } catch (error) {
    console.error('Error in content moderation:', error);
    return { 
      isOffensive: false,
      offendingWords: []
    };
  }
}; 